# **✅ Task 16: Hyperparameter Tuning using GridSearchCV:**

## **Import Required Modules:**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

## **Load dataset and apply basic preprocessing:**

In [2]:
data=load_breast_cancer(as_frame=True)
df=data.frame

In [3]:
X=df.drop(columns="target")
y=df["target"]

In [5]:
numerical_features = X.select_dtypes(include=['float64']).columns
categorical_features = X.select_dtypes(include=['int64']).columns

In [7]:
ss = StandardScaler().set_output(transform="pandas")

In [8]:
X_scaled=ss.fit_transform(X)
X_scaled

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,...,1.901185,0.117700,1.752563,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,...,1.536720,2.047399,1.421940,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,...,0.561361,1.374854,0.579001,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,...,1.961239,2.237926,2.303601,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,...,-1.410893,0.764190,-1.432735,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207

## **Split data into training and testing sets:**

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)

## **Define parameter grid for tuning and apply GridSearchCV:**

In [11]:
clf = GridSearchCV(SVC(gamma="auto"),{"C":[1,10,20],"kernel":["rbf","linear"]},cv=5,return_train_score=False)

In [12]:
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [14]:
results = pd.DataFrame(clf.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015680,0.004512,0.008747,0.002165,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.978022,0.967033,0.989011,0.989011,0.945055,0.973626,0.016447,1
1,0.026431,0.004325,0.014161,0.003589,1,linear,"{'C': 1, 'kernel': 'linear'}",0.967033,0.967033,0.989011,0.967033,0.945055,0.967033,0.013900,3
2,0.033225,0.006567,0.016915,0.011819,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.978022,0.978022,0.989011,0.978022,0.945055,0.973626,0.014906,1
3,0.016517,0.006504,0.005512,0.002188,10,linear,"{'C': 10, 'kernel': 'linear'}",0.967033,0.967033,0.989011,0.978022,0.934066,0.967033,0.018388,3
4,0.009808,0.002609,0.005601,0.002682,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.967033,0.978022,0.967033,0.978022,0.934066,0.964835,0.016150,5
5,0.016446,0.005625,0.005545,0.002284,20,linear,"{'C': 20, 'kernel': 'linear'}",0.945055,0.923077,0.989011,0.967033,0.934066,0.951648,0.023671,6

In [15]:
results[['params','mean_test_score']]

                          params  mean_test_score
0      {'C': 1, 'kernel': 'rbf'}         0.973626
1   {'C': 1, 'kernel': 'linear'}         0.967033
2     {'C': 10, 'kernel': 'rbf'}         0.973626
3  {'C': 10, 'kernel': 'linear'}         0.967033
4     {'C': 20, 'kernel': 'rbf'}         0.964835
5  {'C': 20, 'kernel': 'linear'}         0.951648

## **Extract best parameters and trained model:**

In [16]:
clf.best_score_

np.float64(0.9736263736263737)

In [17]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [19]:
best_model = clf.best_estimator_
y_pred = best_model.predict(X_test)

In [21]:
tuned_accuracy = accuracy_score(y_test,y_pred)
print("classification Report of best model" ,classification_report(y_test,y_pred))

classification Report of best model               precision    recall  f1-score   support

           0       0.98      0.95      0.96        43
           1       0.97      0.99      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

## **Compare tuned model performance with default model:**

In [22]:
ss = SVC(kernel="linear",C=10)

In [24]:
ss.fit(X_train,y_train)

SVC(C=10, kernel='linear')

In [26]:
y_pred = ss.predict(X_test)

In [29]:
default_accuracy = accuracy_score(y_test,y_pred)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95        43
           1       0.99      0.96      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.97      0.96       114
weighted avg       0.97      0.96      0.97       114

In [30]:
print("accuracy difference is ",(tuned_accuracy-default_accuracy)*100)

accuracy difference is  0.8771929824561431